{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/jquery/jquery-1.11.2.min.js"></script>--}}
{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/bootstrap/js/bootstrap.min.js"></script>--}}
{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/select2/js/select2.min.js"></script>--}}
{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/jquery.bxslider/jquery.bxslider.min.js"></script>--}}
{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/owl.carousel/owl.carousel.min.js"></script>--}}
{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/jquery.countdown/jquery.countdown.min.js"></script>--}}
{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/js/jquery.actual.min.js"></script>--}}
{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/fancyBox/jquery.fancybox.js"></script>--}}
{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/jquery.elevatezoom.js"></script>--}}
{{--<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/js/theme-script.js"></script>--}}

<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/jquery/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/select2/js/select2.min.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/jquery.bxslider/jquery.bxslider.min.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/owl.carousel/owl.carousel.min.js"></script>
<!--<script type="text/javascript" src="assets/lib/jquery.countdown/jquery.countdown.min.js"></script>-->
<!-- COUNTDOWN -->
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/countdown/jquery.plugin.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/countdown/jquery.countdown.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/jquery.elevatezoom.js"></script>
<!-- ./COUNTDOWN -->
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/jquery-ui/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/lib/fancyBox/jquery.fancybox.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/js/jquery.actual.min.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/js/theme-script.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/js/option4.js"></script>
<script type="text/javascript" src="{{url('/')}}/public/front-end/assets/js/myscripts.js"></script>